(() => {
'use strict';
const $=id=>document.getElementById(id);
const S={files:'codeyau-files',current:'codeyau-current',theme:'codeyau-theme',users:'codeyau-users',session:'codeyau-session',model:'codeyau-gemini-model'};
const modes={python:'python',javascript:'javascript',cpp:'text/x-c++src',java:'text/x-java',html:'htmlmixed'};
const exts={python:'py',javascript:'js',cpp:'cpp',java:'java',html:'html'};
const templates={python:'a = 384 + 347\nprint(a)',javascript:'const a = 384 + 347;\nconsole.log(a);',cpp:'#include <iostream>\nint main(){std::cout << 384 + 347 << std::endl;return 0;}',java:'public class Main {\n public static void main(String[] args){\n  System.out.println(384 + 347);\n }\n}',html:'<!doctype html><html><body><h1>Hello, codeyau!</h1></body></html>'};
let files=[{name:'main.py',language:'python',content:templates.python}],current=0,editor=null,pyodide=null,pyodidePromise=null,session=null,authMode='signin';
const get=(k,d='')=>{try{const v=localStorage.getItem(k);return v===null?d:v}catch{return d}};
const set=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
function toast(m,err=false){const b=$('toast');if(!b)return;$('toastText').textContent=m;b.classList.remove('translate-y-20','opacity-0');b.classList.toggle('text-red-300',err);clearTimeout(window.__ct);window.__ct=setTimeout(()=>b.classList.add('translate-y-20','opacity-0'),2200)}
function lang(name){const e=String(name).split('.').pop().toLowerCase();if(['js','mjs'].includes(e))return'javascript';if(['cpp','cc','cxx','c'].includes(e))return'cpp';if(e==='java')return'java';if(['html','htm'].includes(e))return'html';return'python'}
function save(){if(editor&&files[current])files[current].content=editor.getValue();set(S.files,JSON.stringify(files));set(S.current,String(current))}
function load(){try{const a=JSON.parse(get(S.files,'null'));if(Array.isArray(a)&&a.length)files=a.map(f=>({name:String(f.name||'main.py'),language:modes[f.language]?f.language:lang(f.name),content:String(f.content||'')}));const i=Number(get(S.current,'0'));if(i>=0&&i<files.length)current=i}catch{}}
function status(){if(!editor||!files[current])return;const c=editor.getCursor(),t=editor.getValue();$('statusFile').textContent=files[current].name;$('statusLanguage').textContent={python:'Python 3',javascript:'JavaScript',cpp:'C++',java:'Java',html:'HTML / CSS / JS'}[files[current].language];$('statusPosition').textContent=`Ln ${c.line+1}, Col ${c.ch+1}`;$('statusStats').textContent=`${t.split('\n').length} lines · ${t.trim()?t.trim().split(/\s+/).length:0} words`}
function render(){const l=$('fileList'),t=$('tabs');if(!l||!t)return;l.innerHTML='';t.innerHTML='';files.forEach((f,i)=>{const r=document.createElement('div');r.className='flex items-center gap-2 px-3 py-2 rounded-lg text-sm cursor-pointer '+(i===current?'bg-indigo-600/20 text-indigo-300':'text-slate-400 hover:bg-slate-800');const n=document.createElement('span');n.textContent=f.name;n.className='truncate flex-1';const d=document.createElement('button');d.innerHTML='<i class="fa-solid fa-xmark"></i>';d.className='text-slate-500 hover:text-red-400';if(files.length===1)d.classList.add('invisible');d.onclick=e=>{e.stopPropagation();delFile(i)};r.append(n,d);r.onclick=()=>switchFile(i);l.appendChild(r);const tab=document.createElement('button');tab.textContent=f.name;tab.className='px-4 h-full text-xs border-t-2 whitespace-nowrap '+(i===current?'bg-slate-950 text-white border-indigo-500':'bg-slate-900 text-slate-400 border-transparent');tab.onclick=()=>switchFile(i);t.appendChild(tab)});status()}
function switchFile(i){if(i===current)return;save();current=i;$('language').value=files[current].language;editor.setOption('mode',modes[files[current].language]);editor.setValue(files[current].content);render();save()}
function addFile(){const name=(prompt('File name:',`file${files.length+1}.py`)||'').trim();if(!name)return;if(!/^[A-Za-z0-9._-]+$/.test(name))return toast('Invalid file name.',true);if(files.some(f=>f.name.toLowerCase()===name.toLowerCase()))return toast('File already exists.',true);const l=lang(name);files.push({name,language:l,content:templates[l]||''});current=files.length-1;$('language').value=l;editor.setOption('mode',modes[l]);editor.setValue(files[current].content);render();save()}
function delFile(i){if(files.length===1)return toast('Keep at least one file.',true);if(!confirm(`Delete ${files[i].name}?`))return;files.splice(i,1);current=Math.min(current,files.length-1);$('language').value=files[current].language;editor.setOption('mode',modes[files[current].language]);editor.setValue(files[current].content);render();save()}
function log(x,type='info'){const e=document.createElement('pre');e.className='m-0 whitespace-pre-wrap '+(type==='error'?'text-red-400':type==='success'?'text-emerald-400':'text-slate-300');e.textContent=String(x);$('console').appendChild(e);$('console').scrollTop=$('console').scrollHeight}
function clear(){ $('console').innerHTML='<div class="text-slate-500 italic">Console cleared.</div>' }
async function python(code){if(!pyodide){if(pyodidePromise)return pyodidePromise;if(typeof loadPyodide!=='function')throw Error('Python runtime failed to load.');pyodidePromise=loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.26.2/full/'}).then(x=>pyodide=x).finally(()=>pyodidePromise=null)}const p=await pyodidePromise||pyodide;let out='',err='';p.setStdout({batched:s=>out+=s});p.setStderr({batched:s=>err+=s});p.setStdin({stdin:()=>String($('stdin').value||'')});try{await p.runPythonAsync(code)}catch(e){if(out)log(out);if(err)log(err,'error');throw e}if(out)log(out);if(err)log(err,'error');log('✓ Python execution completed.','success')}
function javascript(code){return new Promise(resolve=>{const f=document.createElement('iframe');f.hidden=true;document.body.appendChild(f);const token=String(Date.now()+Math.random()),done=()=>{window.removeEventListener('message',on);f.remove();resolve()},on=e=>{if(e.source!==f.contentWindow||e.data?.token!==token)return;if(e.data.type==='log')log(e.data.value);if(e.data.type==='error')log(e.data.value,'error');if(e.data.type==='done')done()};window.addEventListener('message',on);f.srcdoc=`<script>(()=>{const t=${JSON.stringify(token)},s=(a,b)=>parent.postMessage({token:t,type:a,value:b},'*');console.log=(...a)=>s('log',a.join(' '));console.error=(...a)=>s('error',a.join(' '));try{${String(code)}}catch(e){s('error',e.stack||e.message||String(e))}finally{s('done','')}})();<\/script>`})}
function dec(s){try{return decodeURIComponent(escape(atob(s)))}catch{return atob(s)}}
async function compiled(l,code){const r=await fetch('https://ce.judge0.com/submissions?base64_encoded=true&wait=true',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({language_id:l==='cpp'?54:62,source_code:btoa(unescape(encodeURIComponent(code))),stdin:btoa(unescape(encodeURIComponent($('stdin').value||'')))})});if(!r.ok)throw Error(`Compiler service HTTP ${r.status}`);const x=await r.json();if(x.stdout)log(dec(x.stdout));if(x.stderr)log(dec(x.stderr),'error');if(x.compile_output)log(dec(x.compile_output),'error');if(x.message)log(x.message,'error');if(x.status?.id===3)log('✓ Program completed.','success');else if(x.status)log(`Status: ${x.status.description||'Execution failed'}`,'error')}
async function run(){save();clear();$('preview').classList.add('hidden');$('console').classList.remove('hidden');$('runBtn').disabled=true;const f=files[current];log(`▶ Running ${f.name}...`);try{if(f.language==='python')await python(f.content);else if(f.language==='javascript')await javascript(f.content);else if(f.language==='html'){$('preview').classList.remove('hidden');$('previewTab').classList.remove('hidden');$('consoleTab').classList.add('hidden');$('previewFrame').srcdoc=f.content}else await compiled(f.language,f.content)}catch(e){log(e?.stack||e?.message||String(e),'error')}finally{$('runBtn').disabled=false;save()}}
function download(n,c,t){const u=URL.createObjectURL(new Blob([c],{type:t})),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),700)}
function exportFile(){save();download(files[current].name,files[current].content,'text/plain');toast('File exported.')}
function exportProject(){save();download('codeyau-project.json',JSON.stringify({version:1,files},null,2),'application/json');toast('Project exported.')}
function importProject(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.files)||!p.files.length)throw Error('Invalid project file.');files=p.files.map(f=>({name:String(f.name||'file.txt'),language:modes[f.language]?f.language:lang(f.name),content:String(f.content||'')}));current=0;$('language').value=files[0].language;editor.setOption('mode',modes[files[0].language]);editor.setValue(files[0].content);render();save();toast('Project imported.')}catch(e){toast(e.message,true)}};r.readAsText(file)}
function share(){save();const data=btoa(unescape(encodeURIComponent(JSON.stringify(files[current])))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const u=`${location.origin}${location.pathname}#share=${data}`;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(u).then(()=>toast('Share link copied.')).catch(()=>prompt('Copy link:',u));else prompt('Copy link:',u)}
function theme(){const light=get(S.theme,'dark')==='light';$('app').classList.toggle('bg-slate-50',light);$('app').classList.toggle('bg-slate-950',!light);$('themeIcon').className=light?'fa-solid fa-moon':'fa-solid fa-sun';if(editor)editor.setOption('theme',light?'eclipse':'dracula')}
function toggleTheme(){set(S.theme,get(S.theme,'dark')==='light'?'dark':'light');theme()}
function openAI(){if(!$('aiMessages').children.length){const b=document.createElement('div');b.className='rounded-xl p-3 bg-slate-800 text-sm';b.textContent='Ready. Ask me about your code.';$('aiMessages').appendChild(b)}$('aiDrawer').classList.remove('hidden')}
function closeAI(){$('aiDrawer').classList.add('hidden')}
function addAI(t,r){const b=document.createElement('div');b.className='rounded-xl p-3 text-sm '+(r==='user'?'bg-indigo-600/20':'bg-slate-800');b.textContent=t;$('aiMessages').appendChild(b);$('aiMessages').scrollTop=$('aiMessages').scrollHeight}
async function askAI(p){addAI(p,'user');$('aiSend').disabled=true;save();try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:p,language:files[current].language,fileName:files[current].name,code:files[current].content,model:get(S.model,'gemini-3.6-flash')})});const x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||`AI service HTTP ${r.status}`);addAI(x.text||'No response.','assistant')}catch(e){addAI(`AI error: ${e.message}`,'assistant')}finally{$('aiSend').disabled=false}}
function openSettings(){$('geminiKey').value='';$('geminiModel').value=get(S.model,'gemini-3.6-flash');$('settingsModal').classList.remove('hidden');$('settingsModal').classList.add('flex')}
function closeSettings(){$('settingsModal').classList.add('hidden');$('settingsModal').classList.remove('flex')}
function saveSettings(){set(S.model,$('geminiModel').value.trim()||'gemini-3.6-flash');closeSettings();toast('Settings saved.')}
function users(){try{return JSON.parse(get(S.users,'{}'))}catch{return{}}}
async function hash(p,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:100000,hash:'SHA-256'},k,256);return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function updateAccount(){$('accountText').textContent=session?(session.name||'Account'):'Sign in'}
function closeAccount(){$('accountModal').classList.add('hidden');$('accountModal').classList.remove('flex')}
function setAuth(m){authMode=m;$('authTitle').textContent=m==='signup'?'Create account':'Sign in';$('authName').classList.toggle('hidden',m!=='signup');$('authSubmit').textContent=m==='signup'?'Create account':'Sign in';$('authSwitch').textContent=m==='signup'?'Already have an account? Sign in':'Create account';$('authError').classList.add('hidden')}
function account(){if(session){if(confirm(`Signed in as ${session.email}. Sign out?`)){session=null;localStorage.removeItem(S.session);updateAccount();toast('Signed out.')}return}$('accountModal').classList.remove('hidden');$('accountModal').classList.add('flex');setAuth('signin')}
async function submitAuth(){try{const name=$('authName').value.trim(),email=$('authEmail').value.trim().toLowerCase(),pass=$('authPassword').value,a=users();if(pass.length<6||!email)throw Error('Enter an email and password of at least 6 characters.');if(authMode==='signup'){if(!name)throw Error('Enter your name.');if(a[email])throw Error('Account already exists.');const salt=crypto.randomUUID();a[email]={name,email,salt,hash:await hash(pass,salt)};set(S.users,JSON.stringify(a));session={name,email}}else{const u=a[email];if(!u)throw Error('Account not found.');if(await hash(pass,u.salt)!==u.hash)throw Error('Incorrect password.');session={name:u.name,email}}set(S.session,JSON.stringify(session));closeAccount();updateAccount();toast('Signed in.')}catch(e){$('authError').textContent=e.message;$('authError').classList.remove('hidden')}}
function init(){
  load();try{session=JSON.parse(get(S.session,'null'))}catch{session=null}updateAccount();
  if(!window.CodeMirror){toast('Code editor library failed to load.',true);return}
  editor=CodeMirror.fromTextArea($('editor'),{mode:modes[files[current].language],theme:get(S.theme,'dark')==='light'?'eclipse':'dracula',lineNumbers:true,autoCloseBrackets:true,matchBrackets:true,styleActiveLine:true,indentUnit:4,tabSize:4,viewportMargin:30});
  editor.setValue(files[current].content);editor.on('change',()=>{files[current].content=editor.getValue();status();clearTimeout(window.__save);window.__save=setTimeout(save,400)});editor.on('cursorActivity',status);$('language').value=files[current].language;render();theme();
  $('menuBtn').onclick=()=>$('sidebar').classList.toggle('sidebar-collapsed');
  $('newFileBtn').onclick=addFile;$('resetBtn').onclick=()=>{if(confirm('Reset workspace?')){localStorage.removeItem(S.files);localStorage.removeItem(S.current);location.reload()}};$('importBtn').onclick=()=>$('importInput').click();$('importInput').onchange=e=>{if(e.target.files[0])importProject(e.target.files[0]);e.target.value=''};
  $('saveBtn').onclick=()=>{save();toast('Project saved locally.')};$('exportBtn').onclick=exportFile;$('shareBtn').onclick=share;$('runBtn').onclick=run;$('clearBtn').onclick=clear;
  $('themeBtn').onclick=toggleTheme;$('settingsBtn').onclick=openSettings;$('settingsClose').onclick=closeSettings;$('settingsCancel').onclick=closeSettings;$('settingsSave').onclick=saveSettings;
  $('accountBtn').onclick=account;$('authClose').onclick=closeAccount;$('authSubmit').onclick=submitAuth;$('authSwitch').onclick=()=>setAuth(authMode==='signin'?'signup':'signin');
  $('aiBtn').onclick=openAI;$('aiClose').onclick=closeAI;$('aiCloseBackdrop').onclick=closeAI;$('aiSend').onclick=()=>{const p=$('aiInput').value.trim();if(p){$('aiInput').value='';askAI(p)}};document.querySelectorAll('.aiQuick').forEach(b=>b.onclick=()=>askAI(b.dataset.prompt));
  $('consoleTab').onclick=()=>{$('console').classList.remove('hidden');$('preview').classList.add('hidden')};$('previewTab').onclick=()=>{$('preview').classList.remove('hidden');$('console').classList.add('hidden')};
  $('language').onchange=()=>{save();const l=$('language').value,f=files[current],base=f.name.includes('.')?f.name.slice(0,f.name.lastIndexOf('.')):f.name;f.language=l;f.name=`${base}.${exts[l]}`;f.content=templates[l]||f.content;editor.setOption('mode',modes[l]);editor.setValue(f.content);render();save()};
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();toast('Project saved locally.')}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run()}});window.addEventListener('beforeunload',save);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
